# Generated by Django 5.2 on 2025-04-27 15:48

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to=user.models.new_photo_path),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
