# Generated by Django 5.2 on 2025-04-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_photos_author_alter_photos_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='photo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_photos'),
        ),
    ]
