# Generated by Django 5.2 on 2025-04-28 13:38

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_perfil_photo_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='photo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.new_photo_profile_path),
        ),
    ]
