# Generated by Django 5.2 on 2025-04-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_photos_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='link',
            new_name='like',
        ),
    ]
