# Generated by Django 5.2 on 2025-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_link_photos_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='user.perfil'),
        ),
    ]
