# Generated by Django 5.2 on 2025-05-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_photos_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
