# Generated by Django 5.2 on 2025-05-06 11:33

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_photo',
            field=models.ImageField(upload_to=user.models.new_story_path),
        ),
    ]
